DROP TABLE IF EXISTS `#__neukomtemplating_templates`;

CREATE TABLE `#__neukomtemplating_templates` ( 
    `id` SERIAL NOT NULL, 
    `name` VARCHAR(50) NOT NULL,
    `template` TEXT NOT NULL,
    `header` TEXT NOT NULL,
    `footer` TEXT NOT NULL,
    `detail_template` TEXT NOT NULL,
    `tablename` VARCHAR(40) NOT NULL,
    `enable_search` BOOLEAN NOT NULL,
    `enable_pagination` BOOLEAN NOT NULL DEFAULT 0,
    `page_size` INT DEFAULT 0,
    `fields` TEXT NOT NULL,
    `url_parameters` TEXT NOT NULL,
    `condition` VARCHAR(500) NOT NULL,
    `show_detail_page` BOOLEAN,
    `allow_edit` BOOLEAN,
    `allow_create` BOOLEAN,
    `form_send_behaviour` VARCHAR(25) NOT NULL DEFAULT 'list_on_both',
    `access` INT NOT NULL DEFAULT 1,
    `joined_tables` TEXT,
    `id_field_name` VARCHAR(40) NOT NULL,
    `sorting` VARCHAR(80) NOT NULL,
    `limit` INT,
    `user_id_link_field` VARCHAR(40) NOT NULL,
    `contact_email_field` VARCHAR(50) NOT NULL,
    `contact_display_name` VARCHAR(50) NOT NULL,
    `notification_trigger` VARCHAR(20) NOT NULL,
    `notification_recipients` TEXT NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB; 